### PR TITLE
rename function now also supports sql class

### PR DESCRIPTION
**Pull request by milanwiedemann**

### CODE REVIEW

**Comment by milanwiedemann** [comment]
@ChrisBeeley this is a very simple way to check for class of the data object and in case it is sql look somewhere else for the variable names to support the dbply/dplyr rename function

**Comment by milanwiedemann** [comment]
I'm not sure it it will always be this easy or not even sure if this is the best approach, maybe need to talk to dbplyr expert at some point and also learn more about how to use class() properly in R

**Comment by milanwiedemann** [comment]
but this was simple and ... it works so I'm happy

**Comment by ChrisBeeley** [comment]
Yeah, looks good to me. In the long run we could maybe think about asking for some input, don't know from whom though :man_shrugging:

**Comment by ChrisBeeley** [comment]
I filed an issue to keep the discussion in one place, and added @Lextuga007

**Pull request merged**
